version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: go-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ENV_FILEPATH: /absolute/path/to/.env
      ENVIRONMENT: development
      PORT: 8080
      DB_CONNECTION: "user:password@tcp(127.0.0.1:3306)/database?parseTime=true"
      GOOSE_DRIVER: mysql
      GOOSE_DBSTRING: user:password@/database
      GOOSE_MIGRATION_DIR: ./sql/migrations
      CIPHER_SECRET_KEY: my32digitkey12345678901234567890
      INITIALIZATION_VECTOR: my16digitIvKey12
      JWT_SECRET_KEY: mysecretkey

volumes:
  db_data:
