// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package mysqldb

import (
	"database/sql"
	"time"
)

type Task struct {
	ID               string
	Summary          string
	AssignedToUserID sql.NullString
	CreatedByUserID  string
	FinishedAt       sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type User struct {
	ID        string
	Role      uint8
	Name      string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
