basePath: /api/v1
info:
  contact:
    email: danielmesquitta123@gmail.com
    name: Daniel Mesquita
  description: This is a CRUD API for tasks.
  title: Tasks API
  version: "1.0"
paths: {}
swagger: "2.0"
